[profile.default]
src = "pkg"
out = "out"
libs = ["lib"]
via_ir = true

[doc]
out = "docs-out"
title = "Faucet Public Docs"
repository = "https://github.com/fluidity-money/faucet-public"

revert-strings = "debug"
